import SwiftUI
#if os(iOS)
import AVFoundation
import UIKit
#elseif os(macOS)
import AppKit
import Cocoa
#endif
import Foundation

#if os(iOS)
private typealias KokoroAudioPlayer = AVAudioPlayer
#elseif os(macOS)
private typealias KokoroAudioPlayer = NSSound
#endif

// Import createWavData from SummaryService

struct SummaryColumnView: View {
    @EnvironmentObject var appState: AppState
    
    // TTS state variables for summary
    @State private var isSynthesizingSpeech: Bool = false
    @State private var isSpeakingLocally: Bool = false
    @State private var speechSynthesisError: String? = nil
#if os(iOS)
    @State private var audioPlayer: AVAudioPlayer?
    @State private var localSpeechSynth: AVSpeechSynthesizer?
    @StateObject private var soundDelegate = SoundDelegate()
    // Holds the next chunk for fast-start playback sequencing
    @State private var nextAudioChunk: Data? = nil
    @State private var ttsCanceled: Bool = false
    @State private var localTTSTask: Task<Void, Never>? = nil
#elseif os(macOS)
    @State private var audioPlayer: NSSound?
    @State private var localSpeechSynth: NSSpeechSynthesizer?
    @StateObject private var soundDelegate = SoundDelegate()
    // Holds the next chunk for fast-start playback sequencing
    @State private var nextAudioChunk: Data? = nil
    @State private var ttsCanceled: Bool = false
    @State private var localTTSTask: Task<Void, Never>? = nil
#endif

    @State private var showSelectionAskAIResponse = false
    @State private var isSelectionAskAIInFlight = false
    @State private var selectionAskAIResponse: String?
    @State private var selectionAskAIError: String?
    @State private var selectionAskAITask: Task<Void, Never>?

    private var shouldShowExplicitWebAIControls: Bool {
        appState.settings.selectedSummaryProvider != .webAI
    }


    var body: some View {
        VStack(alignment: .leading) {
            if let article = appState.selectedArticle {
                Text("Summary for:")
                    .font(.headline)
                    .padding(.bottom, 2)
                Text(article.title)
                    .font(.subheadline)
                    .foregroundColor(.secondary)
                    .lineLimit(2)
                    .padding(.bottom, 8)
                
                if appState.isLoading {
                    let streamText = appState.mlxStreamingText
                    if (appState.settings.selectedSummaryProvider == .mlxLocal || appState.settings.selectedSummaryProvider == .coreAIMLXLocal) && !streamText.isEmpty {
                        ScrollView {
                            Text(streamText)
                                .font(.body)
                                .foregroundStyle(.primary)
                                .frame(maxWidth: .infinity, alignment: .leading)
                                .padding()
                        }
                    } else {
                        ProgressView("Generating summary...")
                            .padding()
                    }
                } else if appState.isWaitingForAppleIntelligence {
                    VStack(spacing: 8) {
                        ProgressView()
                        Text(appState.appleIntelligenceWaitProgress)
                            .foregroundColor(.secondary)
                            .font(.caption)
                    }
                    .frame(maxWidth: .infinity)
                    .padding()
                } else if let summary = article.summary,
                          !summary.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                    VStack(alignment: .leading) {
                        // Show if summary came from cloud
                        if appState.isSummaryFromCloud {
                            HStack {
                                Image(systemName: "cloud.fill")
                                    .foregroundColor(.blue)
                                Text("Generated by Apple Intelligence")
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                            .padding(.horizontal)
                            .padding(.top, 8)
                        }
                        
                        HStack(spacing: 12) {
                            // Cloud Summary button
                            Button {
                                appState.requestSummary(for: article)
                            } label: {
                                Label("Cloud Summary", systemImage: "cloud.fill")
                            }
                            .buttonStyle(LiquidGlassButtonStyle())
                            .help("Generate summary using Apple Intelligence")

                            if shouldShowExplicitWebAIControls {
                                Button {
                                    appState.requestWebSummary(for: article)
                                } label: {
                                    Label(appState.settings.selectedWebAIProvider.displayName, systemImage: "globe")
                                }
                                .buttonStyle(LiquidGlassButtonStyle())
                                .help("Generate article summary with \(appState.settings.selectedWebAIProvider.displayName)")
                            }
                            
                            // Cloud TTS button
                            Button {
                                speakSummary()
                            } label: {
                                Label("Cloud TTS", systemImage: "speaker.wave.2")
                            }
                            .buttonStyle(LiquidGlassButtonStyle())
                            .ttsActiveGlow(isSynthesizingSpeech, color: .blue)
                            .help("Read aloud (Cloud)")
                            .disabled(isSynthesizingSpeech || isSpeakingLocally)
                            
                            // Stop button
                            Button {
                                stopSummarySpeech()
                            } label: {
                                Label("Stop", systemImage: "stop.fill")
                            }
                            .buttonStyle(LiquidGlassButtonStyle())
                            .help("Stop speech")
                            
                            // Local TTS button
                            Button {
                                speakSummaryLocally(summary)
                            } label: {
                                Label("Local TTS", systemImage: "speaker.wave.2.circle")
                            }
                            .buttonStyle(LiquidGlassButtonStyle())
                            .ttsActiveGlow(isSpeakingLocally, color: .green)
                            .help("Read aloud (Local)")
                            .disabled(isSynthesizingSpeech)


                            
                            // Copy button
                            Button {
                                copyToClipboard(summary)
                            } label: {
                                Label("Copy Summary", systemImage: "doc.on.doc")
                            }
                            .buttonStyle(LiquidGlassButtonStyle())
                            .help("Copy summary")
                        }
                        .padding(.horizontal)
                        .onAppear {
                            // Reset cloud flag when switching articles
                            appState.isSummaryFromCloud = false
                        }
                        
                        ScrollView {
                            SelectableText(.init(summary))
                                .padding()
                                .onAskAI { selection in
                                    askAIFromSummaryColumnSelection(selection, article: article, action: .standard)
                                }
                                .onAskAIWeb { selection in
                                    askAIFromSummaryColumnSelection(selection, article: article, action: .web)
                                }
                        }
                        .frame(maxHeight: .infinity)
                        
                        // TTS status indicators
                        if isSynthesizingSpeech {
                            HStack {
                                ProgressView()
                                    .scaleEffect(0.7)
                                    .padding(.trailing, 5)
                                Text("Reading summary...")
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                            .padding(.horizontal)
                            .padding(.bottom, 4)
                        } else if isSpeakingLocally {
                            HStack {
                                ProgressView()
                                    .scaleEffect(0.7)
                                    .padding(.trailing, 5)
                                Text("Reading with local TTS...")
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                            .padding(.horizontal)
                            .padding(.bottom, 4)
                        }
                        
                        if let error = speechSynthesisError {
                            Text(error)
                                .font(.caption)
                                .foregroundColor(.red)
                                .padding(.horizontal)
                                .padding(.bottom, 4)
                        }

                        // Throughput badge for on-device providers
                        let _colProvider = appState.settings.selectedSummaryProvider
                        if (_colProvider == .mlxLocal || _colProvider == .coreAIMLXLocal || _colProvider == .appleLocal || _colProvider == .applePCCGateway || _colProvider == .summarizeDaemon),
                           !appState.mlxLastThroughput.isEmpty {
                            HStack(spacing: 4) {
                                Image(systemName: "cpu").font(.caption2)
                                Text(appState.mlxLastThroughput).font(.caption2).monospacedDigit()
                            }
                            .foregroundStyle(.secondary)
                            .padding(.horizontal)
                            .padding(.bottom, 6)
                        }
                    }
                }
            } else {
                Text("Select an article to see its summary.")
                    .foregroundColor(.secondary)
                    .padding()
            }
            Spacer()
        }
        .frame(minWidth: 300)
        .padding()
        .overlay(
            VStack {
                if appState.showFallbackNotification {
                    HStack {
                        Image(systemName: "arrow.triangle.2.circlepath")
                            .foregroundColor(.orange)
                            .font(.caption)
                        Text(appState.fallbackNotification)
                            .font(.caption)
                            .foregroundColor(.primary)
                            .multilineTextAlignment(.leading)
                    }
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(.ultraThinMaterial)
                    .cornerRadius(8)
                    .shadow(color: .black.opacity(0.1), radius: 4, x: 0, y: 2)
                    .padding(.horizontal, 16)
                    .transition(.move(edge: .top).combined(with: .opacity))
                    .animation(.spring(response: 0.6, dampingFraction: 0.8), value: appState.showFallbackNotification)
                }
                Spacer()
            }
        )
        .onAppear {
            // Set up sound delegate callbacks
            #if os(iOS)
            soundDelegate.onPlaybackFinished = {
                DispatchQueue.main.async {
                    // If we have a queued chunk (fast-start), play it next
                    if let next = self.nextAudioChunk {
                        self.nextAudioChunk = nil
                        self.playAudio(data: next)
                    } else {
                        self.isSynthesizingSpeech = false
                    }
                }
            }
            soundDelegate.onSpeechFinished = {
                DispatchQueue.main.async {
                    self.isSpeakingLocally = false
                }
            }
            #elseif os(macOS)
            soundDelegate.onPlaybackFinished = {
                DispatchQueue.main.async {
                    if let next = self.nextAudioChunk {
                        self.nextAudioChunk = nil
                        self.playAudio(data: next)
                    } else {
                        self.isSynthesizingSpeech = false
                    }
                }
            }
            soundDelegate.onSpeechFinished = {
                DispatchQueue.main.async {
                    self.isSpeakingLocally = false
                }
            }
            #endif
        }
        .sheet(isPresented: $showSelectionAskAIResponse) {
            AskAIResponseSheet(
                isLoading: isSelectionAskAIInFlight,
                response: selectionAskAIResponse,
                errorMessage: selectionAskAIError,
                onClose: { showSelectionAskAIResponse = false },
                onCopy: copySelectionAskAIResponse
            )
        }
    }
    
    // MARK: - TTS Methods
    
    private func speakSummary() {
        ttsCanceled = false
        guard let article = appState.selectedArticle, 
              let summary = article.summary, 
              !summary.isEmpty else {
            speechSynthesisError = "No summary available to read."
            return
        }
        
        // Stop any currently playing sounds before starting a new one
        #if os(iOS)
        audioPlayer?.stop()
        audioPlayer = nil
        localSpeechSynth?.stopSpeaking(at: .immediate)
        #elseif os(macOS)
        audioPlayer?.stop()
        audioPlayer = nil
        ShortcutsTTS.shared.stopSpeaking()
        localSpeechSynth?.stopSpeaking()
        #endif
        
        isSynthesizingSpeech = true
        isSpeakingLocally = false
        speechSynthesisError = nil
        
        Task {
            // Fast-start: get an early first chunk, then queue the remaining audio.
            await appState.summaryService.synthesizeSpeechFastStartSplit(
                text: summary,
                onFirstChunk: { data in
                    DispatchQueue.main.async {
                        self.playAudio(data: data)
                    }
                },
                onRemainingReady: { data in
                    DispatchQueue.main.async {
                        if let player = self.audioPlayer, player.isPlaying {
                            self.nextAudioChunk = data
                        } else {
                            self.playAudio(data: data)
                        }
                    }
                },
                onComplete: {
                    // Nothing to do; playback finished callback will clear state
                },
                onError: { error in
                    DispatchQueue.main.async {
                        self.speechSynthesisError = "Speech synthesis failed: \(error.localizedDescription)"
                        self.isSynthesizingSpeech = false
                        self.nextAudioChunk = nil
                    }
                }
            )
        }
    }
    
    private func stopSummarySpeech() {
        ttsCanceled = true
        #if os(iOS)
        audioPlayer?.stop()
        audioPlayer = nil
        localSpeechSynth?.stopSpeaking(at: .immediate)
        #elseif os(macOS)
        audioPlayer?.stop()
        audioPlayer = nil
        ShortcutsTTS.shared.stopSpeaking()
        localSpeechSynth?.stopSpeaking()
        #endif
        nextAudioChunk = nil
        isSynthesizingSpeech = false
        isSpeakingLocally = false
    }
    
    private func playAudio(data: Data) {
        #if os(iOS)
        // Stop any existing playback
        audioPlayer?.stop()
        
        // Detect format and handle accordingly
        let audioData: Data
        if isMP3Data(data) || isAACData(data) {
            // OpenAI returns MP3 or AAC directly - both are supported by AVAudioPlayer
            audioData = data
        } else {
            // Gemini returns PCM that needs WAV conversion
            audioData = createWavData(from: data, sampleRate: 24000, channels: 1, bitsPerSample: 16)
        }
        
        do {
            audioPlayer = try AVAudioPlayer(data: audioData)
            if let player = audioPlayer {
                player.prepareToPlay()
                player.delegate = soundDelegate
                if player.play() {
                    // isSynthesizingSpeech remains true until playback finishes or fails
                } else {
                    speechSynthesisError = "Failed to start audio playback."
                    isSynthesizingSpeech = false // Playback failed to start
                }
            }
        } catch {
            speechSynthesisError = "Failed to initialize audio player: \(error.localizedDescription)"
            isSynthesizingSpeech = false // Player initialization failed
        }
        #elseif os(macOS)
        // Stop any existing playback
        audioPlayer?.stop()
        
        // Detect format and handle accordingly
        let audioData: Data
        if isMP3Data(data) || isAACData(data) {
            // OpenAI returns MP3 or AAC directly - both are supported by NSSound
            audioData = data
        } else {
            // Gemini returns PCM that needs WAV conversion
            audioData = createWavData(from: data, sampleRate: 24000, channels: 1, bitsPerSample: 16)
        }
        
        audioPlayer = NSSound(data: audioData)
        if let player = audioPlayer {
            player.delegate = soundDelegate
            if player.play() {
                // isSynthesizingSpeech remains true until playback finishes or fails
            } else {
                speechSynthesisError = "Failed to start audio playback."
                isSynthesizingSpeech = false // Playback failed to start
            }
        } else {
            speechSynthesisError = "Failed to initialize audio player with data."
            isSynthesizingSpeech = false // Player initialization failed
        }
        #endif
    }
    
    private func speakSummaryLocally(_ text: String) {
        #if os(iOS)
        // Check if Kokoro engine is selected
        let settings = PersistenceManager.shared.loadSettings()
        if settings.localTTSEngine == .kokoro {
            guard KokoroTTSService.shared.isAvailable else {
                isSpeakingLocally = false
                speechSynthesisError = "MLX TTS is not available. Add the MLXAudio package and model access."
                return
            }
            if isSpeakingLocally {
                localTTSTask?.cancel()
                localTTSTask = nil
                audioPlayer?.stop()
                localSpeechSynth?.stopSpeaking(at: .immediate)
                isSpeakingLocally = false
                return
            }
            guard !text.isEmpty else {
                speechSynthesisError = "No summary available to read."
                return
            }
            audioPlayer?.stop()
            isSpeakingLocally = true
            isSynthesizingSpeech = false
            startKokoroPlayback(
                text: text,
                voice: settings.kokoroVoice,
                speed: settings.kokoroSpeed,
                setAudioPlayer: { player in audioPlayer = player },
                soundDelegate: soundDelegate,
                taskStore: &localTTSTask,
                onCompleted: {
                    isSpeakingLocally = false
                    localTTSTask = nil
                },
                onError: { message in
                    speechSynthesisError = message
                    isSpeakingLocally = false
                }
            )
            return
        }

        // Check if running on Mac as iPad app - use Shortcuts instead
        var isRunningOnMac = false
        if #available(iOS 14.0, *) {
            isRunningOnMac = ProcessInfo.processInfo.isiOSAppOnMac
        }
        
        if isRunningOnMac {
            // Toggle off if already speaking (can't really stop shortcuts)
            if isSpeakingLocally {
                ShortcutsTTS.shared.stopSpeaking()
                isSpeakingLocally = false
                return
            }
            
            guard !text.isEmpty else {
                speechSynthesisError = "No summary available to read."
                return
            }
            
            // Stop any other audio playing
            audioPlayer?.stop()
            
            // Start speaking via Shortcuts
            isSpeakingLocally = true
            isSynthesizingSpeech = false
            
            let success = ShortcutsTTS.shared.speakText(text) {
                // Completion handler - called when speech ends (estimated)
                DispatchQueue.main.async {
                    self.isSpeakingLocally = false
                }
            }
            
            if !success {
                isSpeakingLocally = false
                speechSynthesisError = "Failed to start Shortcuts TTS"
            }
            
            return
        }
        
        // Original iOS code for real devices
        // Toggle off if already speaking
        if isSpeakingLocally {
            localSpeechSynth?.stopSpeaking(at: .immediate)
            isSpeakingLocally = false
            return
        }
        
        guard !text.isEmpty else {
            speechSynthesisError = "No summary available to read."
            return
        }
        
        // Stop any other audio playing
        audioPlayer?.stop()
        
        // Initialize speech synthesizer
        if localSpeechSynth == nil {
            localSpeechSynth = AVSpeechSynthesizer()
            localSpeechSynth?.delegate = soundDelegate
        }
        
        let utterance = AVSpeechUtterance(string: text)
        utterance.rate = 0.52  // Slightly slower for clarity
        utterance.pitchMultiplier = 1.0
        utterance.volume = 1.0
        utterance.preUtteranceDelay = 0.0
        utterance.postUtteranceDelay = 0.0

        // Use saved voice from settings (same as other views)
        if let savedVoiceID = UserDefaults.standard.string(forKey: "LocalTTS.iOSOnMac.SelectedVoiceID"),
           !savedVoiceID.isEmpty,
           let savedVoice = AVSpeechSynthesisVoice(identifier: savedVoiceID) {
            // Only skip com.apple.voice on Mac (they don't work there)
            if ProcessInfo.processInfo.isiOSAppOnMac && savedVoice.identifier.contains("com.apple.voice") {
                print("🔊 [SummaryColumn] Skipping com.apple.voice on Mac")
            } else {
                utterance.voice = savedVoice
                let qualityStr = savedVoice.quality == .premium ? "PREMIUM" : 
                                savedVoice.quality == .enhanced ? "Enhanced" : "Default"
                print("🔊 [SummaryColumn] Using saved voice: \(savedVoice.name) [\(qualityStr)]")
            }
        }
        
        // If no saved voice, find the best available
        if utterance.voice == nil {
            let currentLang = AVSpeechSynthesisVoice.currentLanguageCode()
            let allVoices = AVSpeechSynthesisVoice.speechVoices()
            
            // Filter for current language (and exclude com.apple.voice on Mac)
            let availableVoices: [AVSpeechSynthesisVoice]
            if ProcessInfo.processInfo.isiOSAppOnMac {
                availableVoices = allVoices.filter { 
                    $0.language == currentLang && !$0.identifier.contains("com.apple.voice")
                }
            } else {
                availableVoices = allVoices.filter { $0.language == currentLang }
            }
            
            // Simple priority: Premium > Enhanced > Default
            let premiumVoices = availableVoices.filter { $0.quality == .premium }
            let enhancedVoices = availableVoices.filter { $0.quality == .enhanced }
            
            if let premium = premiumVoices.first {
                utterance.voice = premium
                print("🔊 [SummaryColumn] Using PREMIUM voice: \(premium.name)")
            } else if let enhanced = enhancedVoices.first {
                utterance.voice = enhanced
                print("🔊 [SummaryColumn] Using Enhanced voice: \(enhanced.name)")
            } else {
                utterance.voice = AVSpeechSynthesisVoice(language: currentLang)
                if let v = utterance.voice {
                    print("🔊 [SummaryColumn] Using default voice: \(v.name)")
                }
            }
        }
        
        isSpeakingLocally = true
        isSynthesizingSpeech = false
        if let synth = localSpeechSynth {
            DispatchQueue.main.async { synth.speak(utterance) }
        } else {
            isSpeakingLocally = false
            speechSynthesisError = "Failed to initialize speech synthesizer."
        }
        #elseif os(macOS)
        // Check if Kokoro engine is selected
        let settings = PersistenceManager.shared.loadSettings()
        if settings.localTTSEngine == .kokoro {
            guard KokoroTTSService.shared.isAvailable else {
                isSpeakingLocally = false
                speechSynthesisError = "MLX TTS is not available. Add the MLXAudio package and model access."
                return
            }
            if isSpeakingLocally {
                localTTSTask?.cancel()
                localTTSTask = nil
                audioPlayer?.stop()
                isSpeakingLocally = false
                return
            }
            guard !text.isEmpty else {
                speechSynthesisError = "No summary available to read."
                return
            }
            audioPlayer?.stop()
            isSpeakingLocally = true
            isSynthesizingSpeech = false
            startKokoroPlayback(
                text: text,
                voice: settings.kokoroVoice,
                speed: settings.kokoroSpeed,
                setAudioPlayer: { player in audioPlayer = player },
                soundDelegate: soundDelegate,
                taskStore: &localTTSTask,
                onCompleted: {
                    isSpeakingLocally = false
                    localTTSTask = nil
                },
                onError: { message in
                    speechSynthesisError = message
                    isSpeakingLocally = false
                }
            )
            return
        }

        // Toggle off if already speaking (CLI shortcut cannot truly stop mid-stream)
        if isSpeakingLocally {
            ShortcutsTTS.shared.stopSpeaking()
            isSpeakingLocally = false
            return
        }

        guard !text.isEmpty else {
            speechSynthesisError = "No summary available to read."
            return
        }

        // Stop all other audio
        audioPlayer?.stop()

        isSpeakingLocally = true
        isSynthesizingSpeech = false

        let success = ShortcutsTTS.shared.speakText(text) {
            DispatchQueue.main.async {
                self.isSpeakingLocally = false
            }
        }

        if !success {
            isSpeakingLocally = false
            speechSynthesisError = "Failed to start Shortcuts TTS on macOS."
        }
        #endif
    }
    
    private func copyToClipboard(_ text: String) {
        #if os(iOS)
        UIPasteboard.general.string = text
        #elseif os(macOS)
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(text, forType: .string)
        #endif
    }

    private func startKokoroPlayback(
        text: String,
        voice: String,
        speed: Double,
        setAudioPlayer: @escaping (KokoroAudioPlayer?) -> Void,
        soundDelegate: SoundDelegate,
        taskStore: inout Task<Void, Never>?,
        onCompleted: @escaping () -> Void,
        onError: @escaping (String) -> Void
    ) {
        _ = soundDelegate
        taskStore?.cancel()
        taskStore = Task {
            defer {
                if !PersistenceManager.shared.loadSettings().kokoroPrecacheEnabled {
                    KokoroTTSService.shared.unloadIfAllowed()
                }
                Task { @MainActor in
                    onCompleted()
                }
            }
            do {
                let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
                guard !trimmed.isEmpty else { return }

                func makeKokoroChunks(from input: String) -> [String] {
                    let firstSize = min(240, input.count)
                    let firstChunk = String(input.prefix(firstSize))
                    let remaining = String(input.dropFirst(firstSize)).trimmingCharacters(in: .whitespacesAndNewlines)
                    guard !remaining.isEmpty else { return [firstChunk] }

                    var chunks: [String] = [firstChunk]
                    let sentences = remaining.components(separatedBy: CharacterSet(charactersIn: ".!?"))
                    var current = ""
                    let maxChunkSize = 420
                    for sentence in sentences {
                        let trimmedSentence = sentence.trimmingCharacters(in: .whitespacesAndNewlines)
                        if trimmedSentence.isEmpty { continue }
                        let sentenceWithPunctuation = trimmedSentence + "."
                        if current.count + sentenceWithPunctuation.count <= maxChunkSize {
                            current += (current.isEmpty ? "" : " ") + sentenceWithPunctuation
                        } else {
                            if !current.isEmpty { chunks.append(current) }
                            current = sentenceWithPunctuation
                        }
                    }
                    if !current.isEmpty { chunks.append(current) }
                    return chunks
                }

                let chunks = makeKokoroChunks(from: trimmed)
                guard let firstChunk = chunks.first else { return }

                func playChunk(_ data: Data) async throws -> TimeInterval {
                    try await MainActor.run {
                        #if os(iOS)
                        do {
                            let player = try AVAudioPlayer(data: data)
                            player.delegate = nil
                            player.prepareToPlay()
                            setAudioPlayer(player)
                            if player.play() == false {
                                onError("Failed to start audio playback.")
                                throw NSError(domain: "KokoroPlayback", code: -1)
                            }
                            return player.duration
                        } catch {
                            onError("Failed to initialize audio player: \(error.localizedDescription)")
                            throw error
                        }
                        #elseif os(macOS)
                        guard let player = NSSound(data: data) else {
                            onError("Failed to initialize audio player.")
                            throw NSError(domain: "KokoroPlayback", code: -1)
                        }
                        setAudioPlayer(player)
                        if player.play() == false {
                            onError("Failed to start audio playback.")
                            throw NSError(domain: "KokoroPlayback", code: -1)
                        }
                        return player.duration
                        #endif
                    }
                }

                enum KokoroPlaybackError: Error { case timeout }

                func synthesizeWithTimeout(_ text: String) async throws -> Data {
                    try await withThrowingTaskGroup(of: Data.self) { group in
                        group.addTask {
                            try await KokoroTTSService.shared.synthesize(
                                text: text,
                                voice: voice,
                                speed: Float(speed)
                            )
                        }
                        group.addTask {
                            try await Task.sleep(nanoseconds: 20_000_000_000)
                            throw KokoroPlaybackError.timeout
                        }
                        let result = try await group.next()!
                        group.cancelAll()
                        return result
                    }
                }

                let firstData = try await synthesizeWithTimeout(firstChunk)
                if Task.isCancelled { return }
                var currentDuration = try await playChunk(firstData)

                if chunks.count == 1 { return }

                var nextIndex = 1
                var nextTask: Task<Data, Error>? = Task {
                    try await synthesizeWithTimeout(chunks[nextIndex])
                }
                defer { nextTask?.cancel() }

                while nextIndex < chunks.count {
                    try await Task.sleep(nanoseconds: UInt64(currentDuration * 1_000_000_000))
                    if Task.isCancelled { return }

                    guard let task = nextTask else { return }
                    let data = try await task.value
                    nextIndex += 1

                    if nextIndex < chunks.count {
                        nextTask = Task {
                            try await synthesizeWithTimeout(chunks[nextIndex])
                        }
                    } else {
                        nextTask = nil
                    }

                    currentDuration = try await playChunk(data)
                }
            } catch {
                if Task.isCancelled { return }
                await MainActor.run {
                    let message: String
                    if let kokoroError = error as? KokoroTTSServiceError, kokoroError == .notAvailable {
                        message = "MLX TTS is not available. Add the MLXAudio package and model access."
                    } else if String(describing: error).contains("timeout") {
                        message = "Kokoro is still loading models. Please wait a moment and try again."
                    } else {
                        message = "Kokoro TTS failed: \(error.localizedDescription)"
                    }
                    onError(message)
                }
            }
        }
    }

    private func summarizeWithSelectedProvider(_ article: Article) {
        appState.requestSummary(for: article)
    }

    private func askAIFromSummaryColumnSelection(_ selection: String, article: Article, action: AskAISelectionAction) {
        let trimmed = selection.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        selectionAskAITask?.cancel()
        isSelectionAskAIInFlight = true
        selectionAskAIResponse = nil
        selectionAskAIError = nil
        showSelectionAskAIResponse = true

        let prompt = appState.articleQAPrompt(
            article: article,
            question: "What is said about \(trimmed)?"
        )

        selectionAskAITask = Task {
            let answer = await withCheckedContinuation { continuation in
                switch action {
                case .standard:
                    appState.askQuestionAboutSelection(prompt: prompt) { response in
                        continuation.resume(returning: response)
                    }
                case .web:
                    appState.askWebQuestionAboutSelection(prompt: prompt, title: "Article Ask AI Web") { response in
                        continuation.resume(returning: response)
                    }
                }
            }

            await MainActor.run {
                self.selectionAskAIResponse = formatAskAIResponseForDisplay(answer)
                self.isSelectionAskAIInFlight = false
            }
        }
    }

    private func copySelectionAskAIResponse() {
        guard let selectionAskAIResponse, !selectionAskAIResponse.isEmpty else { return }
        #if os(iOS)
        UIPasteboard.general.string = selectionAskAIResponse
        #elseif os(macOS)
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(selectionAskAIResponse, forType: .string)
        #endif
    }
    
    private var summaryProviderIcon: String {
        switch appState.settings.selectedSummaryProvider {
        case .gemini:
            return "sparkles"
        case .appleLocal:
            return "cpu"
        case .appleCloud:
            return "cloud.fill"
        case .applePCCGateway:
            return "bolt.horizontal.cloud.fill"
        case .mlxLocal, .coreAIMLXLocal:
            return "memorychip"
        case .webAI:
            return "globe"
        case .summarizeDaemon:
            return "terminal"
        }
    }
    
    private var summaryProviderTintColor: Color {
        switch appState.settings.selectedSummaryProvider {
        case .gemini:
            return .purple.opacity(0.1)
        case .appleLocal:
            return .green.opacity(0.1)
        case .appleCloud:
            return .blue.opacity(0.1)
        case .applePCCGateway:
            return .cyan.opacity(0.14)
        case .mlxLocal, .coreAIMLXLocal:
            return .orange.opacity(0.1)
        case .webAI:
            return .teal.opacity(0.14)
        case .summarizeDaemon:
            return .indigo.opacity(0.14)
        }
    }
}

struct SummaryColumnView_Previews: PreviewProvider {
    static var previews: some View {
        SummaryColumnView()
            .environmentObject(AppState())
            .previewLayout(.sizeThatFits)
    }
}
