import SwiftUI
#if os(iOS)
import AVFoundation
import UIKit

private func ensureBackgroundTTSReady() {
    let audioSession = AVAudioSession.sharedInstance()
    do {
        try audioSession.setCategory(
            .playback,
            mode: .spokenAudio,
            options: [.duckOthers, .allowBluetooth, .allowBluetoothA2DP]
        )
        try audioSession.setActive(true)
    } catch {
        print("🔊 [SummaryColumnView] Failed to configure audio session: \(error)")
    }
}
#elseif os(macOS)
import AppKit
import Cocoa
private func ensureBackgroundTTSReady() {}
#else
private func ensureBackgroundTTSReady() {}
#endif
import Foundation

// Import createWavData from SummaryService

struct SummaryColumnView: View {
    @EnvironmentObject var appState: AppState
    
    // TTS state variables for summary
    @State private var isSynthesizingSpeech: Bool = false
    @State private var isSpeakingLocally: Bool = false
    @State private var speechSynthesisError: String? = nil
    @State private var isAskingSelectionAI = false
    @State private var selectionAskAIPrompt = ""
    @State private var selectionAskAIResponse = ""
    @State private var showSelectionAskAISheet = false
#if os(iOS)
    @State private var audioPlayer: AVAudioPlayer?
    @State private var localSpeechSynth: AVSpeechSynthesizer?
    @StateObject private var soundDelegate = SoundDelegate()
    // Holds the next chunk for fast-start playback sequencing
    @State private var nextAudioChunk: Data? = nil
    @State private var ttsCanceled: Bool = false
    @State private var localTTSTask: Task<Void, Never>? = nil
#elseif os(macOS)
    @State private var audioPlayer: NSSound?
    @State private var localSpeechSynth: NSSpeechSynthesizer?
    @StateObject private var soundDelegate = SoundDelegate()
    // Holds the next chunk for fast-start playback sequencing
    @State private var nextAudioChunk: Data? = nil
    @State private var ttsCanceled: Bool = false
#endif

    private var shouldShowExplicitWebAIControls: Bool {
        appState.settings.selectedSummaryProvider != .webAI
    }


    var body: some View {
        VStack(alignment: .leading) {
            if let article = appState.selectedArticle {
                Text("Summary for:")
                    .font(.headline)
                    .padding(.bottom, 2)
                Text(article.title)
                    .font(.subheadline)
                    .foregroundColor(.secondary)
                    .lineLimit(2)
                    .padding(.bottom, 8)
                
                if appState.isSummarizingArticle(article) {
                    let streamText = appState.mlxStreamingText
                    if (appState.settings.selectedSummaryProvider == .mlxLocal || appState.settings.selectedSummaryProvider == .coreAIMLXLocal) && !streamText.isEmpty {
                        ScrollView {
                            Text(streamText)
                                .font(.body)
                                .foregroundStyle(.primary)
                                .frame(maxWidth: .infinity, alignment: .leading)
                                .padding()
                        }
                    } else {
                        ProgressView("Generating summary...")
                            .padding()
                    }
                } else if appState.isWaitingForAppleIntelligence {
                    VStack(spacing: 8) {
                        ProgressView()
                        Text(appState.appleIntelligenceWaitProgress)
                            .foregroundColor(.secondary)
                            .font(.caption)
                    }
                    .frame(maxWidth: .infinity)
                    .padding()
                } else if let summary = article.summary, !summary.isEmpty {
                    VStack(alignment: .leading) {
                        // Show if summary came from cloud
                        if appState.isSummaryFromCloud {
                            HStack {
                                Image(systemName: "cloud.fill")
                                    .foregroundColor(.blue)
                                Text("Generated by Apple Intelligence")
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                            .padding(.horizontal)
                            .padding(.top, 8)
                        }
                        
                        HStack(spacing: 12) {
                            // Cloud Summary button
                            Button {
                                appState.requestSummary(for: article)
                            } label: {
                                Label("Cloud Summary", systemImage: "cloud.fill")
                            }
                            .buttonStyle(LiquidGlassButtonStyle())
                            .help("Generate summary using Apple Intelligence")

                            if shouldShowExplicitWebAIControls {
                                Button {
                                    appState.requestWebSummary(for: article)
                                } label: {
                                    Label(appState.settings.selectedWebAIProvider.displayName, systemImage: "globe")
                                }
                                .buttonStyle(LiquidGlassButtonStyle())
                                .help("Generate article summary with \(appState.settings.selectedWebAIProvider.displayName)")
                            }
                            
                            // Cloud TTS button
                            Button {
                                speakSummary()
                            } label: {
                                Label("Cloud TTS", systemImage: "speaker.wave.2")
                            }
                            .buttonStyle(LiquidGlassButtonStyle())
                            .ttsActiveGlow(isSynthesizingSpeech, color: .blue)
                            .help("Read aloud (Cloud)")
                            .disabled(isSynthesizingSpeech || isSpeakingLocally)
                            
                            // Stop button
                            Button {
                                stopSummarySpeech()
                            } label: {
                                Label("Stop", systemImage: "stop.fill")
                            }
                            .buttonStyle(LiquidGlassButtonStyle())
                            .help("Stop speech")
                            
                            // Local TTS button
                            Button {
                                speakSummaryLocally(summary)
                            } label: {
                                Label("Local TTS", systemImage: "speaker.wave.2.circle")
                            }
                            .buttonStyle(LiquidGlassButtonStyle())
                            .ttsActiveGlow(isSpeakingLocally, color: .green)
                            .help("Read aloud (Local)")
                            .disabled(isSynthesizingSpeech)


                            
                            // Copy button
                            Button {
                                copyToClipboard(summary)
                            } label: {
                                Label("Copy Summary", systemImage: "doc.on.doc")
                            }
                            .buttonStyle(LiquidGlassButtonStyle())
                            .help("Copy summary")
                        }
                        .padding(.horizontal)
                        .onAppear {
                            // Reset cloud flag when switching articles
                            appState.isSummaryFromCloud = false
                        }
                        
                        ScrollView {
                            SelectableText(
                                text: summary,
                                onAskAI: handleAskAISelection(selectedText:context:),
                                onAskAIWeb: handleAskAIWebSelection(selectedText:context:),
                                textIsPrecleaned: true
                            )
                            .fixedSize(horizontal: false, vertical: true)
                            .padding()
                            .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .frame(maxHeight: .infinity)

                        // On-device throughput badge (MLX + Apple Local)
                        let _provider = appState.settings.selectedSummaryProvider
                        if (_provider == .mlxLocal || _provider == .coreAIMLXLocal || _provider == .appleLocal || _provider == .applePCCGateway),
                           !appState.mlxLastThroughput.isEmpty {
                            HStack(spacing: 4) {
                                Image(systemName: "cpu")
                                    .font(.caption2)
                                Text(appState.mlxLastThroughput)
                                    .font(.caption2)
                                    .monospacedDigit()
                            }
                            .foregroundStyle(.secondary)
                            .padding(.horizontal)
                            .padding(.bottom, 2)
                        }

                        // TTS status indicators
                        if isSynthesizingSpeech {
                            HStack {
                                ProgressView()
                                    .scaleEffect(0.7)
                                    .padding(.trailing, 5)
                                Text("Reading summary...")
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                            .padding(.horizontal)
                            .padding(.bottom, 4)
                        } else if isSpeakingLocally {
                            HStack {
                                ProgressView()
                                    .scaleEffect(0.7)
                                    .padding(.trailing, 5)
                                Text("Reading with local TTS...")
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                            .padding(.horizontal)
                            .padding(.bottom, 4)
                        }
                        
                        if let error = speechSynthesisError {
                            Text(error)
                                .font(.caption)
                                .foregroundColor(.red)
                                .padding(.horizontal)
                                .padding(.bottom, 4)
                        }
                    }
                } else {
                    VStack(spacing: 12) {
                        HStack(spacing: 10) {
                            Button(action: {
                                summarizeWithSelectedProvider(article)
                            }) {
                                HStack {
                                    Image(systemName: summaryProviderIcon)
                                    Text("Summarize Article")
                                }
                                .padding()
                                .frame(maxWidth: .infinity)
                                .applyGlassStyle(cornerRadius: 8, tintColor: summaryProviderTintColor)
                            }

                            if shouldShowExplicitWebAIControls {
                                Button {
                                    appState.requestWebSummary(for: article)
                                } label: {
                                    Image(systemName: "globe")
                                        .font(.subheadline)
                                        .frame(width: 44, height: 44)
                                }
                                .buttonStyle(LiquidGlassButtonStyle())
                                .help("Generate article summary with \(appState.settings.selectedWebAIProvider.displayName)")
                            }
                        }

                    }
                    .padding(.top, 16)
                }
            } else {
                Text("Select an article to see its summary.")
                    .foregroundColor(.secondary)
        .padding()
        .sheet(isPresented: $showSelectionAskAISheet) {
            AskAIResponseSheet(
                question: selectionAskAIPrompt,
                answer: selectionAskAIResponse,
                onCopy: { copyToClipboard(selectionAskAIResponse) }
            )
            #if os(iOS)
            .presentationDetents([.medium, .large])
            .presentationCornerRadius(32)
            #endif
        }
    }
            Spacer()
        }
        .frame(minWidth: 300)
        .padding()
        .askAILoadingOverlay(isAskingSelectionAI)
        .overlay(
            VStack {
                if appState.showFallbackNotification {
                    HStack {
                        Image(systemName: "arrow.triangle.2.circlepath")
                            .foregroundColor(.orange)
                            .font(.caption)
                        Text(appState.fallbackNotification)
                            .font(.caption)
                            .foregroundColor(.primary)
                            .multilineTextAlignment(.leading)
                    }
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(.ultraThinMaterial)
                    .cornerRadius(8)
                    .shadow(color: .black.opacity(0.1), radius: 4, x: 0, y: 2)
                    .padding(.horizontal, 16)
                    .transition(.move(edge: .top).combined(with: .opacity))
                    .animation(.spring(response: 0.6, dampingFraction: 0.8), value: appState.showFallbackNotification)
                }
                Spacer()
            }
        )
        .onAppear {
            // Set up sound delegate callbacks
            #if os(iOS)
            soundDelegate.onPlaybackFinished = {
                DispatchQueue.main.async {
                    // If we have a queued chunk (fast-start), play it next
                    if let next = self.nextAudioChunk {
                        self.nextAudioChunk = nil
                        self.playAudio(data: next)
                    } else {
                        self.isSynthesizingSpeech = false
                    }
                }
            }
            soundDelegate.onSpeechFinished = {
                DispatchQueue.main.async {
                    self.isSpeakingLocally = false
                }
            }
            #elseif os(macOS)
            soundDelegate.onPlaybackFinished = {
                DispatchQueue.main.async {
                    if let next = self.nextAudioChunk {
                        self.nextAudioChunk = nil
                        self.playAudio(data: next)
                    } else {
                        self.isSynthesizingSpeech = false
                    }
                }
            }
            soundDelegate.onSpeechFinished = {
                DispatchQueue.main.async {
                    self.isSpeakingLocally = false
                }
            }
            #endif
        }
    }
    
    // MARK: - TTS Methods
    
    private func speakSummary() {
        ttsCanceled = false
        guard let article = appState.selectedArticle, 
              let summary = article.summary, 
              !summary.isEmpty else {
            speechSynthesisError = "No summary available to read."
            return
        }
        
        // Stop any currently playing sounds before starting a new one
        #if os(iOS)
        audioPlayer?.stop()
        audioPlayer = nil
        localSpeechSynth?.stopSpeaking(at: .immediate)
        #elseif os(macOS)
        audioPlayer?.stop()
        audioPlayer = nil
        localSpeechSynth?.stopSpeaking()
        #endif
        
        isSynthesizingSpeech = true
        isSpeakingLocally = false
        speechSynthesisError = nil
        
        Task {
            // Fast-start: get an early first chunk, then queue the remaining audio.
            await appState.summaryService.synthesizeSpeechFastStartSplit(
                text: summary,
                onFirstChunk: { data in
                    DispatchQueue.main.async {
                        self.playAudio(data: data)
                    }
                },
                onRemainingReady: { data in
                    DispatchQueue.main.async {
                        if let player = self.audioPlayer, player.isPlaying {
                            self.nextAudioChunk = data
                        } else {
                            self.playAudio(data: data)
                        }
                    }
                },
                onComplete: {
                    // Nothing to do; playback finished callback will clear state
                },
                onError: { error in
                    DispatchQueue.main.async {
                        self.speechSynthesisError = "Speech synthesis failed: \(error.localizedDescription)"
                        self.isSynthesizingSpeech = false
                        self.nextAudioChunk = nil
                    }
                }
            )
        }
    }
    
    private func stopSummarySpeech() {
        ttsCanceled = true
        #if os(iOS)
        localTTSTask?.cancel()
        localTTSTask = nil
        KokoroTTSService.shared.cancelPlayback()
        audioPlayer?.stop()
        audioPlayer = nil
        localSpeechSynth?.stopSpeaking(at: .immediate)
        #elseif os(macOS)
        audioPlayer?.stop()
        audioPlayer = nil
        localSpeechSynth?.stopSpeaking()
        #endif
        nextAudioChunk = nil
        isSynthesizingSpeech = false
        isSpeakingLocally = false
    }
    
    private func playAudio(data: Data) {
        #if os(iOS)
        ensureBackgroundTTSReady()
        // Stop any existing playback
        audioPlayer?.stop()
        
        // Detect format and handle accordingly
        let audioData: Data
        if isMP3Data(data) || isAACData(data) {
            // OpenAI returns MP3 or AAC directly - both are supported by AVAudioPlayer
            audioData = data
        } else {
            // Gemini returns PCM that needs WAV conversion
            audioData = createWavData(from: data, sampleRate: 24000, channels: 1, bitsPerSample: 16)
        }
        
        do {
            audioPlayer = try AVAudioPlayer(data: audioData)
            if let player = audioPlayer {
                player.prepareToPlay()
                player.delegate = soundDelegate
                if player.play() {
                    // isSynthesizingSpeech remains true until playback finishes or fails
                } else {
                    speechSynthesisError = "Failed to start audio playback."
                    isSynthesizingSpeech = false // Playback failed to start
                }
            }
        } catch {
            speechSynthesisError = "Failed to initialize audio player: \(error.localizedDescription)"
            isSynthesizingSpeech = false // Player initialization failed
        }
        #elseif os(macOS)
        // Stop any existing playback
        audioPlayer?.stop()
        
        // Detect format and handle accordingly
        let audioData: Data
        if isMP3Data(data) || isAACData(data) {
            // OpenAI returns MP3 or AAC directly - both are supported by NSSound
            audioData = data
        } else {
            // Gemini returns PCM that needs WAV conversion
            audioData = createWavData(from: data, sampleRate: 24000, channels: 1, bitsPerSample: 16)
        }
        
        audioPlayer = NSSound(data: audioData)
        if let player = audioPlayer {
            player.delegate = soundDelegate
            if player.play() {
                // isSynthesizingSpeech remains true until playback finishes or fails
            } else {
                speechSynthesisError = "Failed to start audio playback."
                isSynthesizingSpeech = false // Playback failed to start
            }
        } else {
            speechSynthesisError = "Failed to initialize audio player with data."
            isSynthesizingSpeech = false // Player initialization failed
        }
        #endif
    }
    
    private func speakSummaryLocally(_ text: String) {
        #if os(iOS)
        // Toggle off if already speaking
        if isSpeakingLocally {
            localTTSTask?.cancel()
            localTTSTask = nil
            KokoroTTSService.shared.cancelPlayback()
            localSpeechSynth?.stopSpeaking(at: .immediate)
            isSpeakingLocally = false
            return
        }
        
        guard !text.isEmpty else {
            speechSynthesisError = "No summary available to read."
            return
        }
        
        // Stop any other audio playing
        audioPlayer?.stop()
        localSpeechSynth?.stopSpeaking(at: .immediate)
        ensureBackgroundTTSReady()

        let localEngine = appState.summaryService.getLocalTTSEngine()
        if localEngine == .kokoro {
            guard KokoroTTSService.shared.isAvailable else {
                speechSynthesisError = "MLX TTS is not available. Add the MLXAudio package and model access."
                return
            }
            isSpeakingLocally = true
            isSynthesizingSpeech = false
            speechSynthesisError = nil
            let allowCaching = appState.summaryService.isKokoroPrecacheEnabled()
            startKokoroPlayback(
                text: text,
                voice: appState.summaryService.getKokoroVoice(),
                speed: appState.summaryService.getKokoroSpeed(),
                allowCaching: allowCaching,
                precacheEnabled: allowCaching,
                setAudioPlayer: { [self] player in audioPlayer = player },
                soundDelegate: soundDelegate,
                taskStore: &localTTSTask,
                onCompleted: {
                    self.isSpeakingLocally = false
                    self.localTTSTask = nil
                },
                onError: { message in
                    self.speechSynthesisError = message
                    self.isSpeakingLocally = false
                }
            )
            return
        }

        // Check if running on Mac as iPad app - use Shortcuts instead
        if ProcessInfo.processInfo.isiOSAppOnMac {
            // Toggle off if already speaking (can't really stop shortcuts)
            if isSpeakingLocally {
                ShortcutsTTS.shared.stopSpeaking()
                isSpeakingLocally = false
                return
            }

            // Start speaking via Shortcuts
            isSpeakingLocally = true
            isSynthesizingSpeech = false

            let success = ShortcutsTTS.shared.speakText(text) {
                // Completion handler - called when speech ends (estimated)
                DispatchQueue.main.async {
                    self.isSpeakingLocally = false
                }
            }

            if !success {
                isSpeakingLocally = false
                speechSynthesisError = "Failed to start Shortcuts TTS"
            }

            return
        }
        
        // Initialize speech synthesizer
        if localSpeechSynth == nil {
            localSpeechSynth = AVSpeechSynthesizer()
            localSpeechSynth?.delegate = soundDelegate
        }
        
        let utterance = AVSpeechUtterance(string: text)
        utterance.rate = 0.52  // Slightly slower for clarity
        utterance.pitchMultiplier = 1.0
        utterance.volume = 1.0
        utterance.preUtteranceDelay = 0.0
        utterance.postUtteranceDelay = 0.0

        // Use saved voice from settings (same as other views)
        if let savedVoiceID = UserDefaults.standard.string(forKey: "LocalTTS.iOSOnMac.SelectedVoiceID"),
           !savedVoiceID.isEmpty,
           let savedVoice = AVSpeechSynthesisVoice(identifier: savedVoiceID) {
            // Only skip com.apple.voice on Mac (they don't work there)
            if ProcessInfo.processInfo.isiOSAppOnMac && savedVoice.identifier.contains("com.apple.voice") {
                print("🔊 [SummaryColumn] Skipping com.apple.voice on Mac")
            } else {
                utterance.voice = savedVoice
                let qualityStr = savedVoice.quality == .premium ? "PREMIUM" : 
                                savedVoice.quality == .enhanced ? "Enhanced" : "Default"
                print("🔊 [SummaryColumn] Using saved voice: \(savedVoice.name) [\(qualityStr)]")
            }
        }
        
        // If no saved voice, find the best available
        if utterance.voice == nil {
            let currentLang = AVSpeechSynthesisVoice.currentLanguageCode()
            let allVoices = AVSpeechSynthesisVoice.speechVoices()
            
            // Filter for current language (and exclude com.apple.voice on Mac)
            let availableVoices: [AVSpeechSynthesisVoice]
            if ProcessInfo.processInfo.isiOSAppOnMac {
                availableVoices = allVoices.filter { 
                    $0.language == currentLang && !$0.identifier.contains("com.apple.voice")
                }
            } else {
                availableVoices = allVoices.filter { $0.language == currentLang }
            }
            
            // Simple priority: Premium > Enhanced > Default
            let premiumVoices = availableVoices.filter { $0.quality == .premium }
            let enhancedVoices = availableVoices.filter { $0.quality == .enhanced }
            
            if let premium = premiumVoices.first {
                utterance.voice = premium
                print("🔊 [SummaryColumn] Using PREMIUM voice: \(premium.name)")
            } else if let enhanced = enhancedVoices.first {
                utterance.voice = enhanced
                print("🔊 [SummaryColumn] Using Enhanced voice: \(enhanced.name)")
            } else {
                utterance.voice = AVSpeechSynthesisVoice(language: currentLang)
                if let v = utterance.voice {
                    print("🔊 [SummaryColumn] Using default voice: \(v.name)")
                }
            }
        }
        
        isSpeakingLocally = true
        isSynthesizingSpeech = false
        if let synth = localSpeechSynth {
            DispatchQueue.main.async { synth.speak(utterance) }
        } else {
            isSpeakingLocally = false
            speechSynthesisError = "Failed to initialize speech synthesizer."
        }
        #elseif os(macOS)
        // Toggle off if already speaking
        if isSpeakingLocally {
            localSpeechSynth?.stopSpeaking()
            isSpeakingLocally = false
            return
        }
        
        guard !text.isEmpty else {
            speechSynthesisError = "No summary available to read."
            return
        }
        
        // Stop all other audio
        audioPlayer?.stop()
        
        let synth = NSSpeechSynthesizer()
        
        // Try to use iOS-on-Mac voice first for better quality
        var voiceSet = false
        if let iosVoiceID = ensureIOSOnMacPinnedVoice(), !iosVoiceID.isEmpty {
            if setMacSpeechVoice(synth, identifier: iosVoiceID) {
                voiceSet = true
                print("🔊 [LocalTTS] Using iOS-on-Mac voice: \(iosVoiceID)")
            }
        }
        
        // Fall back to Mac voice selection
        if !voiceSet {
            let override = UserDefaults.standard.string(forKey: "LocalTTS.Mac.SelectedVoiceID") ?? ""
            if !override.isEmpty {
                _ = setMacSpeechVoice(synth, identifier: override)
            } else if let voiceID = preferredMacVoiceIdentifier() {
                _ = setMacSpeechVoice(synth, identifier: voiceID)
            }
        }
        
        synth.delegate = soundDelegate
        
        isSpeakingLocally = true
        isSynthesizingSpeech = false
        if !synth.startSpeaking(text) {
            isSpeakingLocally = false
            speechSynthesisError = "Failed to start local speech synthesis."
        } else {
            localSpeechSynth = synth
        }
        #endif
    }
    
    private func copyToClipboard(_ text: String) {
        #if os(iOS)
        UIPasteboard.general.string = text
        #elseif os(macOS)
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(text, forType: .string)
        #endif
    }
    
    
    private func summarizeWithSelectedProvider(_ article: Article) {
        appState.requestSummary(for: article)
    }

    private func handleAskAISelection(selectedText: String, context: String) {
        runSelectionAskAI(selectedText: selectedText, context: context, useWebPath: false)
    }

    private func handleAskAIWebSelection(selectedText: String, context: String) {
        runSelectionAskAI(selectedText: selectedText, context: context, useWebPath: true)
    }

    private func runSelectionAskAI(selectedText: String, context: String, useWebPath: Bool) {
        guard !isAskingSelectionAI else { return }
        let sourceContext = appState.selectedArticle.map { appState.articleSelectionSourceContext(for: $0) }
        let prompt = buildAskAISelectionPrompt(
            selectedText: selectedText,
            extractedContext: context,
            sourceContext: sourceContext?.text ?? "",
            sourceLabel: sourceContext?.label ?? ""
        )
        guard !prompt.isEmpty else { return }

        selectionAskAIPrompt = prompt
        selectionAskAIResponse = ""
        isAskingSelectionAI = true

        let finish: (String) -> Void = { answer in
            DispatchQueue.main.async {
                self.selectionAskAIResponse = formatAskAIResponseForDisplay(answer)
                self.isAskingSelectionAI = false
                self.showSelectionAskAISheet = true
            }
        }

        if useWebPath {
            appState.askWebQuestionAboutSelection(prompt: prompt, completion: finish)
        } else {
            appState.askQuestionAboutSelection(prompt: prompt, completion: finish)
        }
    }
    
    private var summaryProviderIcon: String {
        switch appState.settings.selectedSummaryProvider {
        case .gemini:
            return "sparkles"
        case .appleLocal:
            return "cpu"
        case .appleCloud:
            return "cloud.fill"
        case .applePCCGateway:
            return "network"
        case .mlxLocal, .coreAIMLXLocal:
            return "memorychip"
        case .webAI:
            return "globe"
        case .summarizeDaemon:
            return "terminal"
        }
    }

    private var summaryProviderTintColor: Color {
        switch appState.settings.selectedSummaryProvider {
        case .gemini:
            return .purple.opacity(0.1)
        case .appleLocal:
            return .green.opacity(0.1)
        case .appleCloud:
            return .blue.opacity(0.1)
        case .applePCCGateway:
            return .cyan.opacity(0.12)
        case .mlxLocal, .coreAIMLXLocal:
            return .orange.opacity(0.1)
        case .webAI:
            return .teal.opacity(0.14)
        case .summarizeDaemon:
            return .indigo.opacity(0.14)
        }
    }
}

struct SummaryColumnView_Previews: PreviewProvider {
    static var previews: some View {
        SummaryColumnView()
            .environmentObject(AppState())
            .previewLayout(.sizeThatFits)
    }
}
